name: timeseries-env
channels:
- conda-forge
- defaults
dependencies:
# --- Python Version ---
- python=3.11

# --- Core Libraries ---
- pandas=2.1.3
- numpy=1.26.3
- scikit-learn=1.3.2
- matplotlib=3.8.2
- seaborn=0.13.0
- statsmodels=0.14.0
- scipy=1.11.4
- xgboost=3.0.0

# --- Time Series Analysis ---
- pmdarima=2.0.3

# --- Deep Learning ---
# 참고: TensorFlow는 pip로 설치합니다 (conda-forge에서 사용 불가)

# --- Data Collection ---
- requests=2.31.0
- pandas-datareader=0.10.0
- yfinance=0.2.35

# --- Jupyter Environment ---
- jupyter=1.0.0
- jupyterlab=4.0.9
- notebook=7.0.6

# --- Utility Libraries ---
- pip=23.3.1
- tqdm=4.66.1
- openpyxl=3.1.2

# --- Pip Dependencies ---
- pip:
  - tensorflow==2.15.0
  - keras==2.15.0
  - keras-tuner==1.3.5

# 이 환경 파일은 conda-forge 채널에서 실제로 사용 가능한 패키지 버전으로 구성되었습니다.
